name: Workouts Poster Generator

on:
  workflow_dispatch:
    inputs:
      lat:
        description: '📍 中心点纬度 (例如: 35.30500318)'
        required: true
        default: '35.30500318'
      lon:
        description: '📍 中心点经度 (例如: 113.93085256)'
        required: true
        default: '113.93085256'
      distance:
        description: '📏 涵盖范围距离(米) (例如: 18000)'
        required: true
        default: '18000'
      city:
        description: '🏙️ 城市名称 (例如: 新乡市)'
        required: true
        default: '新乡市'
      province:
        description: '🗺️ 省份名称 (例如: 河南省)'
        required: true
        default: '河南省'

jobs:
  build_map:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: 获取仓库代码
      uses: actions/checkout@v4

    - name: 设置 Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyarrow duckdb Pillow terraink-py

    - name: 下载最新 data.db
      run: |
        wget https://raw.githubusercontent.com/yaoshubin3574/workouts_page/master/run_page/data.db -O data.db

    - name: 转换 data.db 到 data.parquet
      run: python convert_db.py

    - name: 生成 SVG 海报
      run: |
        python generate_poster.py \
          --lat ${{ github.event.inputs.lat }} \
          --lon ${{ github.event.inputs.lon }} \
          --distance ${{ github.event.inputs.distance }} \
          --city "${{ github.event.inputs.city }}" \
          --province "${{ github.event.inputs.province }}"

    - name: 打包 SVG 并提供下载
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.city }}-Colorful-Map  # 下载压缩包的名字
        path: colorful-map.svg                              # 要打包的文件
        retention-days: 7                                   # 下载链接保留 7 天，之后自动清理不占空间
